### ISSUE TITLE
Dnsmasq fail to start up

### ISSUE THREAD

**Issue by RoninYuan-WY** [xiaorouji/openwrt-package#1523]
用AdguardHome或smartdns做上游DNS服务器时发现，DNS无法解析，查看系统日志发现，

 daemon.crit dnsmasq[1]: cannot access directory /var/etc/dnsmasq-passwall.d: No such file or directory
daemon.crit dnsmasq[1]: FAILED to start up
daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash

但是查看系统中目录及目录内部配置文件确实存在，也查看了cfg01411c，没看到什么特别的错误，而且这些配置都会升级继承下来的。这个问题也是在最近升级feeds重编译openwrt后才出现的。若改成DNS重定向到AdGuardHome可以解决问题。

**Comment by Frank94chan** [comment]
同样的问题，困扰我一个多礼拜了，ImmortalWRT master，只要 passwall 中选择了 dns 过滤就会报和上面一样的 dnsmasq 无法启动的错误。

**Comment by sdhz151** [comment]
支持

**Comment by dumk1217** [comment]
我也是这个问题，不知道怎么解决

**Comment by syazwansaidan93** [comment]
yeah, I facing this issue too, both official openwrt and immortalwrt, luckily it work on lede, but unstable,

**Comment by sdhz151** [comment]
openwrt-21.02（password+helloworld）正常，把openwrt/package/network/services/dnsmasq回退到2.85试试

**Comment by sdhz151** [comment]
openwrt-21.02（password+helloworld）正常，把dnsmasq回退到2.85试试

**Comment by xiaorouji** [comment]
你干脆发固件上来吧，我用的固件无法复现

**Comment by ghost** [comment]
好像ssrp改了/var/etc/dnsmasq-passwall.d路径
https://github.com/immortalwrt/luci/commit/8423fc6924d4617b253e2af6dc8744078ff86b2b

**Comment by handsomeji** [comment]
用最新源码试下

**Comment by syazwansaidan93** [comment]
> 用最新源码试下

okay thank you boss, I will give feedback later ,

**Comment by RoninYuan-WY** [comment]
链接: https://pan.baidu.com/s/181GSr8L0g-Fvdz3pcPmt9g 提取码: 3ck6
试了回退dnsmasq到2.85，以及去除ssrp都不行。以上是最新源码编译的虚拟机上的固件，dnsmasq回退到2.85

**Comment by syazwansaidan93** [comment]
thanks boss, new update does fix this issue. 👍👍👍👍, tested on master openwrt

**Comment by UMU618** [comment]
这个问题，即使今天，在 openwrt 官方的 snapshots 里面的某些新硬件依然存在。

**Comment by lengfwong** [comment]
[oldium](https://github.com/oldium) commented [on 20 Apr](https://github.com/openwrt/openwrt/issues/9726#issuecomment-1103180668)
Dnsmasq is running in a limited environment (procd-ujail), you cannot access any directory freely. The jail environment is controlled in /etc/init.d/dnsmasq, so you can either extend the script to accept custom directories to be part of procd_add_jail_mount, or remove the procd-ujail package, so that the secure/limited environment is not used at all.
