### ISSUE TITLE
shadowsocks-libev: how to config ss_server using "plugins" options?

### ISSUE THREAD

**Issue by hungnm1518** [xiaorouji/openwrt-package#1723]
## 你的功能请求是否与问题有关？ 请描述。

I am not sure if this is a bug or configuration issue. In Server-Side, shadowsocks-libev works but I'm trying to config it with plugins, i.e. obfs-server. But there is no field to configure this.
![image](https://user-images.githubusercontent.com/43890051/149673467-0ddea501-5139-4c09-b0d7-9946f7fb221a.png)
This's luci-app-shadowsocks configuration. And I see there are 2 options to configure the plugins. How to enable this option? Thanks!
![image](https://user-images.githubusercontent.com/43890051/149673258-af89729b-7f0c-41c4-a1e5-75f05f947d45.png)

**Comment by jh0072110** [comment]
I’m confused, if u r in Xhina and u wanna let ur router to be a server, u don’t need plug-in (because ur server and client all in Xhina) and if u r not in Xhina I also think u don’t need this, plug-in is not better for safety, it only makes ur traffic profile more invisible and makes ur server more slow lol, so I think this is not a issue, just no need :P

**Comment by handsomeji** [comment]
I think it is better to use V2ray/Xray.

**Comment by hungnm1518** [comment]
thanks for your reply. I'm using shadowsocks on a device with 8MB flash. So I can't use v2ray or xray. I'll try to make a custom firmware for my issue.  Thanks a lot for your project!

**Comment by smallprogram** [comment]
temporarily close this issue

**Comment by bingzhangdai** [comment]
I have similar requirement, that I am using a shadowsocks [Cloak](https://github.com/cbeuw/Cloak/issues) plugin which only provides a binary to be downloaded. How can I specify the plugin name here?
