### ISSUE TITLE
add iran geoip 

### ISSUE THREAD

**Issue by mmddks** [xiaorouji/openwrt-package#3053]
### 描述你想要的新功能

Hi.
please add geoip and geosite iran 
from this fork
https://github.com/bootmortis/iran-hosted-domains

### 描述你想要的解决方案

Enable this list by default

**Comment by Jasonzhang2023** [comment]
伊朗同胞也是在墙内苦苦挣扎着

**Comment by mmddks** [comment]
Yes, more and harder than China

**Comment by handsomeji** [comment]
You don't need to be so troublesome.

You can get iran's domain name and IP in the Geo repository and add it to the direct list of the rules list.
And then, 
`Use Direct List` checked..
`China List` set `Close(Not use)`, because you don't need.
`TCP Default Proxy Mode` selected `proxy`
`UDP Default Proxy Mode` selected `proxy`
save && apply.
enjoy...

if you want to use the shunt mode of different nodes, recommended to use passwall2.
